apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg4
  namespace: demo
spec:
  version: "4.4.26"
  deletionPolicy: WipeOut
  replicas: 3
  replicaSet:
    name: "rs1"
  podTemplate:
    spec:
      containers:
      - name: mongodb
        resources:
          requests:
            cpu: 700m
            memory: 700Mi
  # coordinator:
  #   resources:
  #     requests:
  #       cpu: 222m
  #       memory: 222Mi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    # storageClassName: linode-block-storage
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
        interval: 10s
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: ClusterIssuer
  #     name: cluster-issuer
  # clusterAuthMode: x509


# kubectl create secret tls mongo-ca \
#      --cert=ca.crt \
#      --key=ca.key \
#      --namespace=cert-manager

# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: mongo-ca-issuer
#   namespace: demo
# spec:
#   ca:
#     secretName: mongo-ca

# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: cluster-issuer
# spec:
#   ca:
#     secretName: mongo-ca

# mongo --tls --tlsCAFile /var/run/mongodb/tls/ca.crt --tlsCertificateKeyFile /var/run/mongodb/tls/client.pem admin --host localhost --authenticationMechanism MONGODB-X509 --authenticationDatabase='$external' -u "CN=arnob,O=kubedb" --quiet