apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg4
  namespace: demo
spec:
  version: "4.4.26"
  deletionPolicy: WipeOut
  replicas: 3
  replicaSet:
    name: "rs1"
  podTemplate:
    spec:
      containers:
      - name: mongodb
        resources:
          requests:
            cpu: 700m
            memory: 700Mi
  # coordinator:
  #   resources:
  #     requests:
  #       cpu: 222m
  #       memory: 222Mi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    # storageClassName: linode-block-storage
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
        interval: 10s