apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-kubedb-all
  namespace: kubedb
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-kubeops-all
  namespace: kubeops
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kubedb-egress
  namespace: kubedb
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress